import type { RubriqueId, RubriqueMeta } from "./guide-types";

export const RUBRIQUES: RubriqueMeta[] = [
  {
    id: "01",
    slug: "01-observer",
    eyebrow: "Rubrique 01",
    title: "S'observer pour se comprendre",
    hook: "Le premier pas. Ralentir, regarder, comprendre — sans juger.",
    cssColor: "var(--ch-observer)",
    hex: "#1B4FE5",
    available: true,
  },
  {
    id: "02",
    slug: "02-hygiene-de-vie",
    eyebrow: "Rubrique 02",
    title: "Prendre soin de soi : hygiène de vie & santé",
    hook: "Sommeil, alimentation, mouvement — la base du fonctionnement.",
    cssColor: "var(--ch-soin)",
    hex: "#B05BC9",
    available: true,
  },
  {
    id: "03",
    slug: "03-emotions-impulsivite",
    eyebrow: "Rubrique 03",
    title: "Réguler son impulsivité & ses émotions",
    hook: "Apprendre à freiner pour choisir sa réponse.",
    cssColor: "var(--ch-emotions)",
    hex: "#FF8AB8",
    available: true,
  },
  {
    id: "04",
    slug: "04-attention-memoire",
    eyebrow: "Rubrique 04",
    title: "Développer son attention & sa mémoire",
    hook: "Protéger, canaliser, soutenir — pas réparer.",
    cssColor: "var(--ch-attention)",
    hex: "#FF1F8F",
    available: true,
  },
  {
    id: "05",
    slug: "05-motivation-action",
    eyebrow: "Rubrique 05",
    title: "Motivation et action",
    hook: "Démarrer, finir, traverser les coups de mou.",
    cssColor: "var(--ch-motivation)",
    hex: "#E8294E",
    available: false,
  },
  {
    id: "06",
    slug: "06-organiser-temps",
    eyebrow: "Rubrique 06",
    title: "S'organiser et gérer son temps",
    hook: "Apprivoiser la cécité au temps.",
    cssColor: "var(--ch-temps)",
    hex: "#F26B2C",
    available: false,
  },
  {
    id: "07",
    slug: "07-environnement",
    eyebrow: "Rubrique 07",
    title: "Gérer l'environnement",
    hook: "Structurer l'espace pour libérer l'attention.",
    cssColor: "var(--ch-environnement)",
    hex: "#F0B340",
    available: false,
  },
  {
    id: "08",
    slug: "08-interactions",
    eyebrow: "Rubrique 08",
    title: "Interaction et communication",
    hook: "Conversations, conflits, lien social — apprivoiser.",
    cssColor: "var(--ch-interactions)",
    hex: "#4DD0B0",
    available: false,
  },
  {
    id: "09",
    slug: "09-evolution",
    eyebrow: "Rubrique 09",
    title: "Suivre son évolution",
    hook: "Mesurer le chemin parcouru, ajuster.",
    cssColor: "var(--ch-evolution)",
    hex: "#14B8A6",
    available: false,
  },
  {
    id: "10",
    slug: "10-controle",
    eyebrow: "Rubrique 10",
    title: "Reprendre le contrôle",
    hook: "Synthèse — incarner durablement ce qui a marché.",
    cssColor: "var(--ch-controle)",
    hex: "#1FBF7A",
    available: false,
  },
];

export const RUBRIQUE_BY_SLUG: Record<string, RubriqueMeta> = Object.fromEntries(
  RUBRIQUES.map((r) => [r.slug, r]),
);

export const RUBRIQUE_BY_ID: Record<RubriqueId, RubriqueMeta> = Object.fromEntries(
  RUBRIQUES.map((r) => [r.id, r]),
) as Record<RubriqueId, RubriqueMeta>;
